package com.github.aha.poc.itext;

import java.io.FileNotFoundException;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;

@DisplayName("simple PDF generation")
public class SimpleTests extends AbstractTest {

	public static final String RESULT = RESULT_PATH + "/hello.pdf";

	@Test
	public void testSimpleHelloWorld() throws Exception {
		Document document = new Document(createDocument(RESULT));
		document.add(new Paragraph("Simple PDF generated by iText 7!"));
		document.close();
	}

	private PdfDocument createDocument(String targetFilename) throws FileNotFoundException {
		PdfWriter writer = new PdfWriter(targetFilename, buildWriterProperties());
		return new PdfDocument(writer);
	}

}
